# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favorite',
            new_name='is_fav',
        ),
    ]
